language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

script:
  - python setup.py build
  - pip install flake8 flake8-future-import  # matches tests_require in setup.py, a bit hacky
  - python setup.py flake8
